####################################################################
# joshuto: https://github.com/kamiyaa/joshuto
# configs: https://github.com/kamiyaa/joshuto/tree/main/config
####################################################################
numbered_command = true

use_trash = true
watch_files = true
xdg_open = false
xdg_open_fork = false


[display]
# default, hsplit
mode = "default"
automatically_count_files = false
collapse_preview = true

# ratios for parent view (optional), current view and preview
column_ratio = [0, 5, 5]
scroll_offset = 6
show_borders = true
show_hidden = true
show_icons = true
tilde_in_titlebar = true

# none, absolute, relative
line_number_style = "none"

[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = true
directories_first = true
reverse = false

[preview]
# 2MB
max_preview_size = 2097152
preview_script = "~/.config/joshuto/preview_file.sh"

[tab]
# inherit, home, root
home_page = "inherit"
