#  ╭──────────────────────────────────────────────────────────────────────────────╮
#  │                                GoNeovimConfig                                │
#  │      docs: https://github.com/akiyosi/goneovim/wiki/Usage#configuration      │
#  ╰──────────────────────────────────────────────────────────────────────────────╯
[Editor]
## 不显示按钮操作栏
BorderlessWindow = true

## 不要显示标题栏
HideTitlebar = true

## 字体: 在 goneovim.lua 中设置
FontFamily = "JetBrainsMono Nerd Font Mono"
FontSize = 16
# Letterspace = 0
DisableLigatures = false

## 使用系统剪切板
Clipboard = true

## 透明度(0-1)
Transparent = 1

## 允许用 Alt 映射快捷键
Macmeta = true

# 在这些模式下可以使用输入法
# "normal",
# "insert",
# "replace",
# "visual",
# "visual_select",
# "cmdline_normal",
# "cmdline_insert",
# "cmdline_replace"
ModeEnablingIME = [
  "normal",
  "insert",
  "replace",
  "visual",
  "visual_select",
  "cmdline_normal",
  "cmdline_insert",
  "cmdline_replace"
]

## 启动 goneovim 完成后执行已下 vimscript
Ginitvim = '''
lua << EOF
vim.g.isGoNeovim = 1
require("goneovim")
EOF
'''

[Cursor]
## 移动光标平滑过度动画
SmoothMove = false

## 动画持续时间
Duration = 55

[MiniMap]
# 是否禁用 MiniMap 地图
Disable = true

[ScrollBar]
# 禁用滚动条
Disable = true
